### ISSUE TITLE
Hope you can write the build step for this project to readme.md.

### ISSUE THREAD

**Issue by heropoo** [Spleefys/llvm-compiler#1]
Hope you can write the build step for this project to readme.md.

**Comment by heropoo** [comment]
When i run `make`  i got this output:
```
bison -d -o parser.cpp parser.y
parser.y:1.1-5: invalid directive: `%code'
parser.y:1.7-14: syntax error, unexpected identifier
make: *** [parser.cpp] Error 1
```

Hope your help!

**Comment by Spleefys** [comment]
This is a study project for a university. I’m going to finish it later and, naturally, I will make Readme, but in general you start it correctly. I don’t know exactly why this error occurs. To start, flex, bison, clang and LLVM version 6.0 must be installed, there may be problems in them.

**Comment by heropoo** [comment]
Yes,according to what you said above and  i use Ubuntu-18.04 install these toolchain:
```
apt-get install flex bison make gcc llvm-6.0 clang g++ zlib1g-dev libncurses5-dev
```
Then I build successfully!

Thanks!

**Comment by Spleefys** [comment]
Excelent!
And i update this compiler, but it still not good at all, because it's made for educational purposes. 
But it works.
